# Generated by Django 4.2.24 on 2025-09-30 18:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HypotheticalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('manufacturer', models.CharField(max_length=200)),
                ('release_year', models.IntegerField(help_text='Enter the year the console was introduced', validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2025)])),
                ('cpu', models.CharField(max_length=200)),
                ('graphics', models.CharField(max_length=200)),
                ('memory', models.CharField(max_length=200)),
                ('launch_rrp_unadjusted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detailed_description', models.TextField()),
                ('brief_description', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted')], default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypothetical_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Rating from 1 (worst) to 10 (best)')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_reviewer', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='spec_a_console.hypotheticalsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
