# Generated by Django 4.2.24 on 2025-09-30 19:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spec_a_console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypotheticalsystem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
