# Generated by Django 4.2.24 on 2025-10-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spec_a_console', '0002_hypotheticalsystem_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hypotheticalsystem',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='systemreview',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='hypotheticalsystem',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='hypotheticalsystem',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='systemreview',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
